#1 Sprint 9first commit controllers-films-users
Kamatari-rin/java-filmorate pull request #1
Opened 2023-04-22 19:17 UTC by Kamatari-rin

2023-04-23 09:06 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохая работа, что доработать:
1) Логи во все контроллеры добавить
2)  ResponseEntity<сущность> так нельзя во многих местах?
3) Поправить что отписал

Буду ждать с правками =)

2023-04-23 09:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Long, Film> filmMap = new HashMap<>();
Модификатор доступа

2023-04-23 09:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    CustomRestExceptionHandler customRestExceptionHandler  = new CustomRestExceptionHandler();
Для чего?

2023-04-23 09:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            } else throw new ValidationException("The film with this id does not exist.");
айди фильма указать желательно

2023-04-23 09:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    CustomRestExceptionHandler customRestExceptionHandler  = new CustomRestExceptionHandler();
Для чего это

2023-04-23 09:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public ResponseEntity<?> create(@Valid @RequestBody User user) {
ResponseEntity<User> так нельзя?

2023-04-23 09:06 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
Тесты еще вот так можно писать (это для примера):

```java
import javax.validation.*;

ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
validator = factory.getValidator();

@Test

public void invalidName() {

	film = Film.builder().name("")
	
			.description("qweq")
			
			.duration(120)
			
			.releaseDate(LocalDate.of(1999, 12, 12))
			
			.build();
	
	violations = validator.validate(film);
	
	  
	
	assertFalse(violations.isEmpty(), violations.toString());
	
	violations.clear();

}
```

2023-04-25 14:09 UTC, Kamatari-rin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Long, Film> filmMap = new HashMap<>();
+ Добавил

2023-04-25 14:11 UTC, Kamatari-rin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    CustomRestExceptionHandler customRestExceptionHandler  = new CustomRestExceptionHandler();
Когда создавал кастомный перехватчик не совсем понял как его подключить к своему коду.

2023-04-25 14:17 UTC, Kamatari-rin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public ResponseEntity<?> create(@Valid @RequestBody User user) {
Да в данном случае действительно можно ? заменить на конкретную сущность.
+ Исправил.

2023-04-25 14:19 UTC, Kamatari-rin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
Спасибо, возьму на вооружение.

2023-04-25 14:30 UTC, Kamatari-rin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            } else throw new ValidationException("The film with this id does not exist.");
+ Добавил

2023-04-26 06:27 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет

2023-05-05 05:01 UTC, merged