Add database
Kamatari-rin/java-filmorate pull request #3
Opened 2023-05-28 18:03 UTC by Kamatari-rin

2023-05-30 11:52 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо, давай обсудим и доработаем =)

- Давай добавим во все методы контроллеров логгирование
- orElseThrow() а какое исключение бросать не указано, выходит будет дефолтная логика, а она нам точно подходит?

2023-05-30 11:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public List<Genre> genreList(Genre genre) {
Название немного не совпадает по логике

2023-05-30 11:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (count == null) {
Может это на уровне выше (в контроллере) делать, чтобы сервис об этом не думал

2023-05-30 11:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return Optional.of(filmStorage.addFilm(film).orElseThrow()).get();
а тут зачем обертка?

2023-05-30 11:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return Optional.of(filmStorage.likeFilm(filmId, userId).orElseThrow()).get();
Тут обертка точно нужна в виде Optional?

2023-05-30 11:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Optional<List<User>> getUserFriendList(Long id);
Точно ли где лист возвращается нам нужен опшионал? Если например результатов нет то может быть лист пустой

2023-05-30 11:52 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +	GENRE_ID INTEGER PRIMARY KEY,
not null ?

2023-05-30 11:52 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
references  - почему их после создания таблиц добавляешь? А не сразу ?

2023-05-30 11:52 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
Почему так?

2023-05-30 11:52 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо, давай обсудим и доработаем =)

- Давай добавим во все методы контроллеров логгирование
- orElseThrow() а какое исключение бросать не указано, выходит будет дефолтная логика, а она нам точно подходит?

2023-05-30 11:52 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо, давай обсудим и доработаем =)

- Давай добавим во все методы контроллеров логгирование
- orElseThrow() а какое исключение бросать не указано, выходит будет дефолтная логика, а она нам точно подходит?

2023-05-30 19:35 UTC, Kamatari-rin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public List<Genre> genreList(Genre genre) {
Это остатки мусора который я забыл убрать. Данный метод нигде не используется.

2023-05-30 19:37 UTC, Kamatari-rin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (count == null) {
А где это вообще в моем коде?

2023-05-30 19:40 UTC, Kamatari-rin commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Optional<List<User>> getUserFriendList(Long id);
Да тут наверно можно без Optional

2023-05-30 19:41 UTC, Kamatari-rin commented on src/main/resources/schema.sql
> +	GENRE_ID INTEGER PRIMARY KEY,
Да действительно, проглядел. Добавлю.

2023-05-30 19:42 UTC, Kamatari-rin commented on src/main/resources/schema.sql
Я несколько статей посмотрел по этому поводу. Там везде в конце добавляли. Ну и мне показалось что так удобнее. Если принципиально все должно быть в таблицах я перенесу.

2023-05-30 19:49 UTC, Kamatari-rin commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
На счет дефолтного orElseThrow() не совсем понял. Вы имеете ввиду что нужно бросать свое исключение там? Но зачем, если мы в принципе понимаем что там может вылететь и можем это отловить в ExceptionHandler?

2023-06-01 10:31 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - на счет orElseThrow ну не критично поэтому пропустим - Зачет!

2023-06-05 17:42 UTC, merged